# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4add575ff7a38289510ffd5373c74b786823c8ce5a9f5e0d5c66c20b9e919aa1d9be1e392002043ee5569c0a0e079c363e725b4ca55c0c8c9a6745091da150d

test:
  secret_key_base: b3d9228af45fd041246586c7f50cfe8ac281ef2a8b68b106fa23b3e665c3f5fe4572c5140f63af40273c0b6d793ff7f756d66438663101cd99729c945c1aa024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
